"""Deterministic cloud control helpers used by the demo API."""

from datetime import datetime, timezone
import re
from typing import Any


def _terraform_name(value: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_]+", "_", value).strip("_").lower()
    return name or "devorbit"


def generate_terraform(requirements: dict[str, Any]) -> str:
    region = requirements["region"]
    instances = requirements["ec2_instances"]
    vpc_cidr = requirements["vpc_cidr"]
    buckets = requirements["s3_buckets"]
    project = _terraform_name(requirements["project_name"])
    nat_gateway = requirements["enable_nat_gateway"]

    lines = [
        '# Generated by DevOrbit AI. Review and run `terraform plan` before applying.',
        'terraform {',
        '  required_providers {',
        '    aws = {',
        '      source  = "hashicorp/aws"',
        '      version = "~> 5.0"',
        '    }',
        '  }',
        '}',
        '',
        'provider "aws" {',
        f'  region = "{region}"',
        '}',
        '',
        'resource "aws_vpc" "main" {',
        f'  cidr_block           = "{vpc_cidr}"',
        '  enable_dns_hostnames = true',
        '  enable_dns_support   = true',
        f'  tags = {{ Name = "{project}-vpc" }}',
        '}',
        '',
        'resource "aws_subnet" "public" {',
        '  vpc_id                  = aws_vpc.main.id',
        '  cidr_block              = cidrsubnet(aws_vpc.main.cidr_block, 8, 1)',
        '  map_public_ip_on_launch = true',
        f'  tags = {{ Name = "{project}-public" }}',
        '}',
        '',
        'resource "aws_security_group" "web" {',
        f'  name   = "{project}-web"',
        '  vpc_id = aws_vpc.main.id',
        '  ingress { from_port = 80, to_port = 80, protocol = "tcp", cidr_blocks = ["0.0.0.0/0"] }',
        '  egress { from_port = 0, to_port = 0, protocol = "-1", cidr_blocks = ["0.0.0.0/0"] }',
        '}',
        '',
    ]

    for index in range(instances):
        lines.extend([
            f'resource "aws_instance" "web_{index + 1}" {{',
            '  ami                    = "ami-0c02fb55956c7d316" # Amazon Linux 2023, us-east-1',
            '  instance_type          = "t3.micro"',
            '  subnet_id              = aws_subnet.public.id',
            '  vpc_security_group_ids = [aws_security_group.web.id]',
            f'  tags = {{ Name = "{project}-web-{index + 1}" }}',
            '}',
            '',
        ])

    for bucket in buckets:
        bucket_name = _terraform_name(bucket)
        lines.extend([
            f'resource "aws_s3_bucket" "{bucket_name}" {{',
            f'  bucket = "{project}-{bucket_name}"',
            '  force_destroy = false',
            f'  tags = {{ Name = "{project}-{bucket_name}" }}',
            '}',
            '',
            f'resource "aws_s3_bucket_public_access_block" "{bucket_name}" {{',
            f'  bucket                  = aws_s3_bucket.{bucket_name}.id',
            '  block_public_acls       = true',
            '  block_public_policy     = true',
            '  ignore_public_acls      = true',
            '  restrict_public_buckets = true',
            '}',
            '',
        ])

    lines.extend([
        '# NAT gateway requested: ' + ("yes" if nat_gateway else "no") + ". Add private subnets before enabling production egress.",
        'output "vpc_id" { value = aws_vpc.main.id }',
    ])
    return "\n".join(lines) + "\n"


def audit_security_config(config: dict[str, Any]) -> list[dict[str, str]]:
    findings: list[dict[str, str]] = []
    if config.get("iam_user_access_keys", 0) > 0:
        findings.append({"severity": "high", "title": "Long-lived IAM access keys", "recommendation": "Prefer short-lived role credentials and rotate existing keys."})
    if config.get("mfa_enabled") is False:
        findings.append({"severity": "high", "title": "MFA is disabled", "recommendation": "Require MFA for the root account and all human IAM identities."})
    if config.get("s3_public_buckets", 0) > 0:
        findings.append({"severity": "critical", "title": "Public S3 bucket exposure", "recommendation": "Enable S3 Block Public Access and review bucket policies."})
    if config.get("security_group_open_ports"):
        findings.append({"severity": "medium", "title": "Broad security group ingress", "recommendation": "Restrict ingress to known CIDR ranges and required ports."})
    if config.get("cloudtrail_enabled") is False:
        findings.append({"severity": "medium", "title": "CloudTrail is disabled", "recommendation": "Enable organization-wide CloudTrail with a protected log bucket."})
    return findings


def simulate_deploy(target: str, branch: str) -> dict[str, Any]:
    timestamp = datetime.now(timezone.utc).isoformat()
    return {
        "status": "queued",
        "target": target,
        "branch": branch,
        "run_id": f"sim-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
        "message": "Simulation only: no GitHub Actions workflow or Docker build was started.",
        "queued_at": timestamp,
    }