"""Deterministic enterprise feature services with safe extension points for LLMs."""

from typing import Any
import re


PROVIDER_CONTEXT = {
    "aws": {"provider": "aws", "resource": "aws_instance", "network": "aws_vpc"},
    "azure": {"provider": "azurerm", "resource": "azurerm_linux_virtual_machine", "network": "azurerm_virtual_network"},
    "gcp": {"provider": "google", "resource": "google_compute_instance", "network": "google_compute_network"},
}


def cloud_architecture_prompt(provider: str, prompt: str) -> str:
    context = PROVIDER_CONTEXT[provider]
    return f"Design a production-grade {provider.upper()} architecture using the {context['provider']} Terraform provider. Include {context['network']} networking, secure compute, observability, and cost controls. User requirements: {prompt}"


def generate_multicloud_terraform(requirements: dict[str, Any]) -> str:
    provider = requirements.get("cloud_provider", "aws")
    context = PROVIDER_CONTEXT[provider]
    project = re.sub(r"[^a-z0-9_]+", "_", requirements.get("project_name", "devorbit").lower()).strip("_") or "devorbit"
    region = requirements.get("region", "us-east-1")
    if provider == "azure":
        location_line = f'  location = "{region}"'
    elif provider == "gcp":
        location_line = f'  region = "{region}"'
    else:
        location_line = f'  region = "{region}"'
    return "\n".join([
        '# Generated by DevOrbit AI. Run terraform fmt and terraform plan before apply.',
        f'terraform {{ required_providers {{ {context["provider"]} = {{ source = "hashicorp/{context["provider"]}" }} }} }}',
        f'provider "{context["provider"]}" {{', location_line, '}', '',
        f'resource "{context["network"]}" "main" {{',
        f'  name = "{project}-network"',
        '}',
    ]) + "\n"


def validate_iac(content: str, output_format: str) -> list[str]:
    errors: list[str] = []
    if not content.strip():
        errors.append("Generated template is empty")
    if output_format == "terraform":
        if content.count("{") != content.count("}"):
            errors.append("Terraform braces are unbalanced")
        if 'provider "' not in content:
            errors.append("Terraform provider block is missing")
    elif output_format == "cloudformation" and not content.strip().startswith("{"):
        errors.append("CloudFormation output is not valid JSON")
    return errors


def self_heal_iac(content: str, output_format: str, max_attempts: int = 3) -> dict[str, Any]:
    attempts = []
    current = content
    for attempt in range(1, max_attempts + 1):
        errors = validate_iac(current, output_format)
        attempts.append({"attempt": attempt, "errors": errors.copy()})
        if not errors:
            return {"content": current, "valid": True, "attempts": attempts, "healed": attempt > 1}
        if output_format == "terraform":
            current = current.strip()
            if 'provider "' not in current:
                current = 'provider "aws" {}\n\n' + current
            opening, closing = current.count("{"), current.count("}")
            if opening > closing:
                current += "\n}" * (opening - closing)
            elif closing > opening:
                current = current.rstrip("}")
        else:
            current = "{}"
    return {"content": current, "valid": not validate_iac(current, output_format), "attempts": attempts, "healed": len(attempts) > 1}


def analyze_finops(resources: list[dict[str, Any]], request: str = "") -> dict[str, Any]:
    rates = {"t2.micro": 8, "t3.micro": 12, "t3.small": 22, "t3.medium": 42, "m5.large": 70, "db.t3.micro": 28, "db.t3.small": 52}
    recommendations = []
    current = 0.0
    optimized = 0.0
    for resource in resources:
        resource_type = str(resource.get("type", "ec2")).lower()
        instance_type = str(resource.get("instance_type", "t3.micro"))
        count = max(1, int(resource.get("count", 1)))
        storage_gb = max(0, float(resource.get("storage_gb", 0)))
        monthly = rates.get(instance_type, 35) * count + storage_gb * 0.08
        current += monthly
        target = "t3.micro" if instance_type in {"t3.medium", "m5.large", "db.t3.small"} else instance_type
        target_cost = rates.get(target, 35) * count + storage_gb * 0.06
        optimized += target_cost
        if target != instance_type or resource.get("idle"):
            recommendations.append({"resource": resource.get("name", resource_type), "action": "right-size" if target != instance_type else "schedule-stop", "current_type": instance_type, "recommended_type": target, "reason": "Lower utilization or idle signal detected.", "estimated_monthly_savings": round(max(0, monthly - target_cost), 2)})
    savings = round(max(0, current - optimized), 2)
    return {"request": request, "current_monthly_cost": round(current, 2), "optimized_monthly_cost": round(optimized, 2), "estimated_savings": savings, "estimated_savings_percent": round((savings / current * 100) if current else 0, 1), "recommendations": recommendations}