import { useState } from 'react';
import axios from 'axios';
import { Activity, AlertTriangle, Box, CheckCircle, Cloud, Code2, DollarSign, Download, GitBranch, LockKeyhole, Play, Plus, ShieldCheck, Terminal, Trash2 } from 'lucide-react';

const API_URL = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';
type CloudNode = { id: string; type: string; label: string; x: number; y: number };
type CanvasEdge = { source: string; target: string };
const palette = ['VPC', 'EC2', 'S3', 'RDS', 'Lambda', 'ELB'];
const icons: Record<string, typeof Cloud> = { VPC: Cloud, EC2: Box, S3: Box, RDS: Box, Lambda: Code2, ELB: Activity };

export default function EnterpriseDashboard() {
  const [tab, setTab] = useState<'canvas' | 'delivery' | 'security' | 'cost'>('canvas');
  const [nodes, setNodes] = useState<CloudNode[]>([{ id: 'vpc-1', type: 'VPC', label: 'Production VPC', x: 50, y: 55 }]);
  const [edges, setEdges] = useState<CanvasEdge[]>([]);
  const [selectedNode, setSelectedNode] = useState<string | null>(null);
  const [finops, setFinops] = useState<{ current_monthly_cost: number; optimized_monthly_cost: number; estimated_savings_percent: number; recommendations: Array<{ resource: string; action: string; estimated_monthly_savings: number }> } | null>(null);
  const [suggestions, setSuggestions] = useState<{ severity: string; title: string; recommendation: string }[]>([]);
  const [iac, setIac] = useState('');
  const [format, setFormat] = useState<'terraform' | 'cloudformation'>('terraform');
  const [logs, setLogs] = useState<string[]>(['[ready] Enterprise workspace online']);
  const [security, setSecurity] = useState<{ score: number; risk: string; failed_controls: number } | null>(null);
  const [forecast, setForecast] = useState<{ month: number; estimate: number }[]>([]);

  const log = (message: string) => setLogs((current) => [`[${new Date().toLocaleTimeString()}] ${message}`, ...current].slice(0, 8));
  const addNode = (type: string, x = 80 + (nodes.length * 35) % 500, y = 90 + (nodes.length * 28) % 230) => setNodes((current) => { const node = { id: `${type.toLowerCase()}-${Date.now()}`, type, label: `${type} ${current.filter((item) => item.type === type).length + 1}`, x, y }; setSelectedNode(node.id); return [...current, node]; });
  const analyze = async () => { const response = await axios.post(`${API_URL}/api/architecture/analyze`, { nodes, edges }); setSuggestions(response.data.suggestions); log(`Architecture analyzed: ${response.data.suggestions.length} suggestion(s)`); };
  const generate = async () => { const response = await axios.post(`${API_URL}/api/generate-iac`, { output_format: format, project_name: 'devorbit-prod', ec2_instances: Math.max(1, nodes.filter((node) => node.type === 'EC2').length), s3_buckets: ['artifacts'], region: 'us-east-1' }); setIac(response.data.content); log(`Generated ${response.data.filename}`); };
  const downloadIac = () => { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([iac], { type: format === 'terraform' ? 'text/plain' : 'application/json' })); link.download = format === 'terraform' ? 'main.tf' : 'template.json'; link.click(); URL.revokeObjectURL(link.href); };
  const pipeline = async (action: 'connect' | 'scan' | 'deploy') => { const response = await axios.post(`${API_URL}/api/pipeline/action`, { action, provider: 'github', repository: 'devorbit-ai/platform', branch: 'main' }); log(`${action}: ${response.data.run_id} simulated`); };
  const runSecurity = async () => { const response = await axios.post(`${API_URL}/api/security/score`, { configuration: { mfa_enabled: false, iam_wildcard_actions: true, open_ingress: true, public_buckets: false, cloudtrail_enabled: true } }); setSecurity(response.data); log(`Security posture scored ${response.data.score}/100`); };
  const runForecast = async () => { const response = await axios.post(`${API_URL}/api/cost/forecast`, { months: 6, resources: [{ type: 'ec2', count: nodes.filter((node) => node.type === 'EC2').length || 1 }, { type: 'rds', count: nodes.some((node) => node.type === 'RDS') ? 1 : 0 }, { type: 's3', count: nodes.some((node) => node.type === 'S3') ? 1 : 0 }] }); setForecast(response.data.forecast); log(`Cost forecast updated: $${response.data.current_monthly_estimate}/month`); };
    const runFinops = async () => { const response = await axios.post(`${API_URL}/api/finops/optimize`, { request: 'Find idle resources and right-size compute', resources: [{ name: 'web-fleet', type: 'ec2', instance_type: 't3.medium', count: Math.max(1, nodes.filter((node) => node.type === 'EC2').length) }, { name: 'database', type: 'rds', instance_type: 'db.t3.small', count: nodes.some((node) => node.type === 'RDS') ? 1 : 0 }] }); setFinops(response.data); log(`FinOps found ${response.data.estimated_savings_percent}% savings potential`); };
    const connectSelected = (targetId: string) => { if (selectedNode && selectedNode !== targetId && !edges.some((edge) => edge.source === selectedNode && edge.target === targetId)) setEdges((current) => [...current, { source: selectedNode, target: targetId }]); };
  const onDrop = (event: React.DragEvent<HTMLDivElement>) => { event.preventDefault(); const type = event.dataTransfer.getData('component'); if (type) { const rect = event.currentTarget.getBoundingClientRect(); addNode(type, event.clientX - rect.left - 50, event.clientY - rect.top - 25); } };

  return <main className="enterprise-page">
    <header className="enterprise-header"><div><p className="eyebrow">DEVORBIT / ENTERPRISE OPERATIONS</p><h1>Ship infrastructure with intent.</h1><p className="muted">Architecture, delivery, security, and cost signals in one operating surface.</p></div><div className="live-pill"><span /> LIVE SYSTEM</div></header>
    <nav className="workspace-tabs">{([['canvas', 'Architecture canvas', Cloud], ['delivery', 'Pipeline manager', GitBranch], ['security', 'IAM guard', LockKeyhole], ['cost', 'Cost forecast', DollarSign]] as const).map(([value, label, Icon]) => <button className={tab === value ? 'active' : ''} key={value} onClick={() => setTab(value)}><Icon size={16} />{label}</button>)}</nav>
    {tab === 'canvas' && <div className="canvas-connection-tools"><span>{selectedNode ? `Source: ${nodes.find((node) => node.id === selectedNode)?.label}` : 'Select a source node'}</span>{nodes.filter((node) => node.id !== selectedNode).map((node) => <button key={node.id} onClick={() => connectSelected(node.id)}>Connect to {node.label}</button>)}</div>}

    {tab === 'canvas' && <section className="enterprise-grid"><div className="panel canvas-panel"><div className="panel-heading"><div><p className="eyebrow">01 / VISUAL BLUEPRINT</p><h2>Cloud architecture canvas</h2></div><button className="secondary-button" onClick={() => void analyze()}><Activity size={15} />Analyze</button></div><div className="canvas-tools">{palette.map((type) => <button draggable onDragStart={(event) => event.dataTransfer.setData('component', type)} key={type}><Plus size={13} />{type}</button>)}</div><div className="architecture-canvas" onDragOver={(event) => event.preventDefault()} onDrop={onDrop}><span className="canvas-hint">Drag components here to compose your blueprint</span>{nodes.map((node) => { const Icon = icons[node.type] || Box; return <div className="canvas-node" style={{ left: node.x, top: node.y }} key={node.id}><Icon size={17} /><span>{node.label}</span><button title="Remove component" onClick={() => setNodes((current) => current.filter((item) => item.id !== node.id))}><Trash2 size={12} /></button></div>; })}</div></div><div className="panel suggestion-panel"><div className="panel-heading"><div><p className="eyebrow">OPTIMIZATION LENS</p><h2>Architecture review</h2></div><ShieldCheck size={20} /></div>{suggestions.length ? suggestions.map((item) => <div className="suggestion" key={item.title}><span className={`severity ${item.severity}`}>{item.severity}</span><strong>{item.title}</strong><p>{item.recommendation}</p></div>) : <div className="empty-state"><Cloud size={28} /><p>Analyze your canvas to reveal resilience, security, and delivery improvements.</p></div>}</div></section>}

    {tab === 'delivery' && <section className="enterprise-grid"><div className="panel delivery-panel"><div className="panel-heading"><div><p className="eyebrow">02 / DELIVERY CONTROL</p><h2>Pipeline manager</h2></div><GitBranch size={20} /></div><div className="repo-card"><div className="repo-icon"><GitBranch /></div><div><strong>devorbit-ai/platform</strong><p className="muted">GitHub / main branch</p></div><CheckCircle className="success-icon" /></div><div className="pipeline-actions"><button className="primary-button" onClick={() => void pipeline('connect')}><GitBranch size={15} />Connect repository</button><button className="secondary-button" onClick={() => void pipeline('scan')}><ShieldCheck size={15} />Run Trivy scan</button><button className="secondary-button" onClick={() => void pipeline('deploy')}><Play size={15} />Stage deployment</button></div><div className="pipeline-steps">{['Source connected', 'Build and scan', 'Approval gate', 'Deploy to cloud'].map((step, index) => <div key={step} className="pipeline-step"><span>{index + 1}</span><strong>{step}</strong><small>{index < 2 ? 'Ready' : 'Awaiting action'}</small></div>)}</div></div><Console logs={logs} /></section>}

    {tab === 'security' && <section className="enterprise-grid"><div className="panel security-hero"><div className="panel-heading"><div><p className="eyebrow">03 / POLICY INTELLIGENCE</p><h2>IAM guard and compliance</h2></div><LockKeyhole size={20} /></div><div className="score-ring"><strong>{security?.score ?? '--'}</strong><span>/ 100</span></div><p className="risk-label">Risk posture: <b>{security?.risk || 'not scanned'}</b></p><button className="primary-button" onClick={() => void runSecurity()}><ShieldCheck size={15} />Scan security controls</button></div><div className="panel audit-list"><h2>Controls evaluated</h2>{['IAM MFA enforcement', 'Wildcard IAM actions', 'Security group ingress', 'S3 public access', 'CloudTrail coverage'].map((control, index) => <div className="control-row" key={control}><span>{control}</span>{security && index < security.failed_controls ? <AlertTriangle size={16} className="warning-icon" /> : <CheckCircle size={16} className={security ? 'success-icon' : 'muted-icon'} />}</div>)}</div></section>}

    {tab === 'cost' && <section className="enterprise-grid"><div className="panel cost-panel"><div className="panel-heading"><div><p className="eyebrow">04 / FINOPS SIGNALS</p><h2>Predictive cost analytics</h2></div><DollarSign size={20} /></div><div className="cost-total">$ {forecast[0]?.estimate.toFixed(2) || '--'}<span>estimated monthly run rate</span></div><div className="bar-chart">{forecast.map((point) => <div className="bar-column" key={point.month}><div className="bar" style={{ height: `${Math.max(12, (point.estimate / (forecast[forecast.length - 1]?.estimate || 1)) * 100)}%` }} /><small>M{point.month}</small></div>)}</div><button className="primary-button" onClick={() => void runForecast()}><Activity size={15} />Generate six-month forecast</button><button className="secondary-button" onClick={() => void runFinops()}><DollarSign size={15} />Optimize resource sizing</button>{finops && <div className="finops-result"><strong>{finops.estimated_savings_percent}% savings potential</strong><span>${finops.optimized_monthly_cost.toFixed(2)} optimized monthly cost</span>{finops.recommendations.map((item) => <small key={item.resource}>{item.resource}: {item.action} · save ${item.estimated_monthly_savings.toFixed(2)}/mo</small>)}</div>}</div><div className="panel iac-panel"><div className="panel-heading"><div><p className="eyebrow">INFRASTRUCTURE AS CODE</p><h2>Generator output</h2></div><div className="button-row"><Code2 size={20} /><button className="icon-button" onClick={downloadIac} disabled={!iac} title="Download generated infrastructure"><Download size={15} /></button></div></div><div className="format-toggle"><button className={format === 'terraform' ? 'selected' : ''} onClick={() => setFormat('terraform')}>Terraform</button><button className={format === 'cloudformation' ? 'selected' : ''} onClick={() => setFormat('cloudformation')}>CloudFormation</button></div><pre>{iac || '# Choose a format and generate a reviewed infrastructure template.'}</pre><button className="secondary-button" onClick={() => void generate()}><Code2 size={15} />Generate {format}</button></div></section>}
  </main>;
}

function Console({ logs }: { logs: string[] }) { return <div className="panel enterprise-console"><div className="panel-heading"><div><p className="eyebrow">ACTIVITY STREAM</p><h2>Operator console</h2></div><Terminal size={20} /></div><div className="console">{logs.map((entry, index) => <div key={`${entry}-${index}`}><span className="console-marker">›</span>{entry}</div>)}</div></div>; }

