import React, { useEffect, useState } from 'react';
import { ArrowRight, BarChart3, BookOpen, Cloud, Code2, Database, GitBranch, LockKeyhole, Network, Radar, Rocket, Server, ShieldCheck, Sparkles, Terminal, Workflow } from 'lucide-react';
import { Link } from 'react-router-dom';

const metrics = [{ value: '99.98%', label: 'control plane uptime' }, { value: '4.2x', label: 'faster architecture review' }, { value: '24/7', label: 'drift awareness' }];
const agents = [
  { icon: Terminal, title: 'Lead Planner Agent', detail: 'Turns intent into PRDs, dependency maps, and skill-matched delivery plans.', path: '/orchestrator', color: 'cyan' },
  { icon: Server, title: 'Cloud Architect Agent', detail: 'Shapes resilient AWS topologies with multi-AZ patterns and clear trade-offs.', path: '/enterprise', color: 'violet' },
  { icon: ShieldCheck, title: 'DevOps IaC Agent', detail: 'Compiles reviewed Terraform, security checks, and deployment-ready workflows.', path: '/cloud-control', color: 'green' },
];
const features = [
  { icon: Workflow, title: 'Multi-Agent Orchestrator', detail: 'LangGraph pipeline for automated cloud planning, architecture design, and agent handoffs.', color: 'cyan', path: '/orchestrator', label: 'Open pipeline' },
  { icon: Network, title: 'Project Digital Twin', detail: 'Continuous live sync between code repositories, delivery tasks, infrastructure, and documentation.', color: 'violet', path: '/digital-twin', label: 'View twin' },
  { icon: BookOpen, title: 'Capstone Academic Suite', detail: 'Generate IEEE SRS documents, research papers, project reports, and viva slide decks.', color: 'amber', path: '/modules', label: 'Open suite' },
  { icon: Rocket, title: 'Startup MVP & GitHub Sync', detail: 'Intelligent backlog allocation mapped to the strengths of every builder on your team.', color: 'rose', path: '/modules', label: 'Sync backlog' },
  { icon: Code2, title: 'Cloud Control & Terraform IaC', detail: 'Generate reviewed HCL, inspect architecture, and surface security findings before apply.', color: 'blue', path: '/cloud-control', label: 'Generate IaC' },
  { icon: BarChart3, title: 'Enterprise FinOps & CIS IDP', detail: 'Live cost estimation, policy guardrails, and compliance signals for confident operations.', color: 'green', path: '/enterprise', label: 'Open FinOps' },
];
const roles = [{ path: '/enterprise', icon: Cloud, label: 'Cloud Architect', detail: 'Design resilient systems' }, { path: '/orchestrator', icon: GitBranch, label: 'DevOps Engineer', detail: 'Ship reliable pipelines' }, { path: '/modules', icon: Code2, label: 'Product Builder', detail: 'Turn ideas into systems' }];

export default function Home() {
  const [tick, setTick] = useState(0);
  const [pointer, setPointer] = useState({ x: 0, y: 0 });
  useEffect(() => { const interval = window.setInterval(() => setTick((value) => value + 1), 3000); return () => window.clearInterval(interval); }, []);
  const handlePointer = (event) => { const bounds = event.currentTarget.getBoundingClientRect(); setPointer({ x: (event.clientX - bounds.left) / bounds.width - 0.5, y: (event.clientY - bounds.top) / bounds.height - 0.5 }); };
  return <main className="home-page" onPointerMove={handlePointer} onPointerLeave={() => setPointer({ x: 0, y: 0 })}>
    <div className="home-noise" /><div className="home-glow glow-a" /><div className="home-glow glow-b" /><div className="home-grid" />
    <div className="home-content">
      <section className="home-hero"><div className="hero-copy"><div className="hero-kicker"><span className="pulse-dot" /> CONTROL PLANE / ONLINE</div><h1>Autonomous Cloud Orchestration & <span>Project Digital Twin Engine.</span></h1><p>DevOrbit AI turns intent into visible architecture, production-ready automation, security guardrails, and living project intelligence.</p><div className="hero-actions"><Link to="/orchestrator" className="hero-primary">Launch Agent Workspace <ArrowRight size={17} /></Link><Link to="/enterprise" className="hero-secondary">Explore Architecture Canvas <Network size={16} /></Link></div><div className="hero-trust"><span><ShieldCheck size={14} /> policy-aware</span><span><Database size={14} /> stateful by design</span><span><Cloud size={14} /> AWS ready</span></div></div><div className="hero-visual" style={{ transform: `perspective(900px) rotateX(${pointer.y * -5}deg) rotateY(${pointer.x * 7}deg)` }}><div className="hero-canvas-label"><span className="pulse-dot" /> LIVE INFRASTRUCTURE GRAPH</div><div className="canvas-grid-lines" /><div className="orbit-core"><Radar size={31} /><span>DEVORBIT<br /><small>AI CONTROL PLANE</small></span></div><div className="orbit-node node-cloud"><Cloud size={18} /><span>Networking</span></div><div className="orbit-node node-sec"><LockKeyhole size={18} /><span>Security policy</span></div><div className="orbit-node node-code"><Code2 size={18} /><span>Terraform HCL</span></div><div className="orbit-node node-db"><Database size={18} /><span>State + data</span></div><div className="orbit-line line-one" /><div className="orbit-line line-two" /><div className="orbit-line line-three" /><div className="orbit-line line-four" /><span className="traffic-packet packet-one" /><span className="traffic-packet packet-two" /><span className="traffic-packet packet-three" /></div></section>
      <section className="agent-showcase"><div className="showcase-heading"><p className="eyebrow">THE AUTONOMOUS CREW</p><h2>Specialists that move as one.</h2></div><div className="agent-grid">{agents.map(({ icon: Icon, title, detail, path, color }) => <Link to={path} className={`agent-card agent-${color}`} key={title}><div className="agent-icon"><Icon size={23} /></div><div><h3>{title}</h3><p>{detail}</p></div><ArrowRight className="agent-arrow" size={17} /></Link>)}</div></section>
      <section className="metrics-ticker">{metrics.map((metric, index) => <div key={metric.label} className="ticker-item"><strong>{index === 1 ? `${(4.2 + tick * 0.1).toFixed(1)}x` : metric.value}</strong><span>{metric.label}</span></div>)}<div className="ticker-live"><span className="pulse-dot" /> telemetry streaming</div></section>
      <section className="feature-section"><div className="section-intro"><p className="eyebrow">THE DEVORBIT SYSTEM</p><h2>Six surfaces. One operating rhythm.</h2><p>Every layer of delivery gets a clearer signal, from the first architectural sketch to the final compliance check.</p></div><div className="feature-strip">{features.map(({ icon: Icon, title, detail, color, path, label }, index) => <Link to={path} className={`feature-card feature-${color}`} key={title}><span className="feature-index">0{index + 1}</span><div className="feature-icon"><Icon size={20} /></div><h2>{title}</h2><p>{detail}</p><span className="feature-arrow">{label} <ArrowRight size={15} /></span></Link>)}</div></section>
      <section className="role-section"><div><p className="eyebrow">START FROM YOUR LENS</p><h2>Choose the work in front of you.</h2></div><div className="role-grid">{roles.map(({ path, icon: Icon, label, detail }) => <Link to={path} className="role-card" key={label}><Icon size={20} /><span><strong>{label}</strong><small>{detail}</small></span><ArrowRight size={16} /></Link>)}</div></section>
      <footer className="home-footer"><Sparkles size={16} /> DevOrbit AI <span>Infrastructure, with a point of view.</span><ShieldCheck size={16} /></footer>
    </div>
  </main>;
}
