# app/agents/orchestrator.py

def cloud_architect_node(state: dict):
    """
    Step 2: Converts Planner strategy into concrete AWS components.
    """
    planner_output = state.get("planner_result", "")
    
    architect_blueprint = """
### ☁️ Cloud Architect Blueprint Generated
- **VPC CIDR:** 10.0.0.0/16 across us-east-1a and us-east-1b
- **Public Subnets:** 10.0.0.0/24 (AZ1), 10.0.1.0/24 (AZ2) with NAT Gateways
- **Private Compute Subnets:** 10.0.2.0/24 (AZ1), 10.0.3.0/24 (AZ2) hosting EC2 Auto Scaling
- **Database Subnets:** 10.0.4.0/24 (AZ1), 10.0.5.0/24 (AZ2) hosting Amazon RDS PostgreSQL Multi-AZ
- **Storage Layer:** Amazon EFS Shared Storage with Mount Targets in both AZs
- **Traffic Routing:** Internet Gateway -> Application Load Balancer -> EC2 Web Servers
"""
    state["architect_result"] = architect_blueprint
    return state

def devops_iac_node(state: dict):
    """
    Step 3: Compiles AWS Blueprint into Production-Ready Terraform HCL.
    """
    terraform_code = """
# Generated by DevOrbit AI DevOps IaC Agent
provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "devorbit_vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  tags = { Name = "DevOrbit-VPC" }
}

resource "aws_db_subnet_group" "rds_subnet" {
  name       = "devorbit-rds-subnet-group"
  subnet_ids = [aws_subnet.private_db_1.id, aws_subnet.private_db_2.id]
}

resource "aws_db_instance" "postgres" {
  allocated_storage    = 20
  engine               = "postgres"
  engine_version       = "15.3"
  instance_class       = "db.t4g.micro"
  multi_az             = true
  db_name              = "devorbitdb"
  username             = "postgres"
  password             = "DevOrbitSecure2026!"
  skip_final_snapshot  = true
}
"""
    state["terraform_code"] = terraform_code
    return state